barclays_glue_dbt:
  target: dev
  outputs:
    dev:
      type: glue
      region: us-east-2
      database: barclays_glue_dbt
      schema: barclays_glue_dbt
      location: s3://assumerole-s3-glue-dbt-athena/dbt/barclays_glue_dbt/
      glue_version: "3.0"
      worker_type: G.1X
      workers: 2
      threads: 1
      session_provisioning_timeout_in_minutes: 5

optm_eu_reader:
  target: dev
  outputs:
    dev:
      type: glue
      region: us-east-2
      database: optm_eu
      schema: optm_eu
      location: s3://philippe-trino/OPTM_EU/
      glue_version: "3.0"
      worker_type: G.1X
      workers: 2
      threads: 1
      session_provisioning_timeout_in_minutes: 5
