optm_eu_reader:
  target: dev
  outputs:
    dev:
      type: athena
      region_name: us-east-2
      database: optm_eu
      schema: optm_eu
      s3_staging_dir: s3://assumerole-s3-glue-dbt-athena/athena-results/
      work_group: primary

barclays_glue_dbt:
  target: dev
  outputs:
    dev:
      type: athena
      region_name: us-east-2
      database: optm_eu
      schema: optm_eu
      s3_staging_dir: s3://assumerole-s3-glue-dbt-athena/athena-results/
      work_group: primary
