barclays_glue_dbt:
  target: dev
  outputs:
    dev:
      type: glue
      region: us-east-2
      schema: "barclays_glue_dbt"
      location: "s3://assumerole-s3-glue-dbt-athena/dbt"
      role_arn: arn:aws:iam::833664315823:role/assumerole-test-cross-account
      glue_version: "5.0"
      worker_type: G.1X
      workers: 2
      threads: 4
      # session_properties:
      #   query_tag: barclays_glue_seed_run